%% EEG Fractal Analysis - boxplots
% https://github.com/Dorsa-Arezooji/EEG-Fractal-Analysis

 close all 
 clear
 clc
 
 load('FDK_HC.mat');
 load('FDK_OCD.mat');
 
figure; 
subplot(2,1,1)
boxplot([FDK_HC{6}(:,4),...
         FDK_HC{7}(:,4),...
         FDK_HC{8}(:,3),FDK_HC{8}(:,4),FDK_HC{8}(:,5),FDK_HC{8}(:,6),FDK_HC{8}(:,7),...
         FDK_HC{9}(:,3),FDK_HC{9}(:,4),FDK_HC{9}(:,5),...
         FDK_HC{10}(:,3),FDK_HC{10}(:,4),FDK_HC{10}(:,5),FDK_HC{10}(:,6),...
         FDK_HC{11}(:,3),FDK_HC{11}(:,4),FDK_HC{11}(:,5)],...
         'Colors','mcrrrrrgggkkkkbbb',...
         'labels',{'F3','F3','F7','F3','Fz','F4','F8','F7','F3','Fz','F7','F3','Fz','F4','F7','F3','Fz'},...
         'BoxStyle','filled')

ylabel('Katz FD (HC)')

subplot(2,1,2)
boxplot([FDK_OCD{6}(:,4),...
         FDK_OCD{7}(:,4),...
         FDK_OCD{8}(:,3),FDK_OCD{8}(:,4),FDK_OCD{8}(:,5),FDK_OCD{8}(:,6),FDK_OCD{8}(:,7),...
         FDK_OCD{9}(:,3),FDK_OCD{9}(:,4),FDK_OCD{9}(:,5),...
         FDK_OCD{10}(:,3),FDK_OCD{10}(:,4),FDK_OCD{10}(:,5),FDK_OCD{10}(:,6),...
         FDK_OCD{11}(:,3),FDK_OCD{11}(:,4),FDK_OCD{11}(:,5)],...
         'Colors','mcrrrrrgggkkkkbbb',...
         'labels',{'F3','F3','F7','F3','Fz','F4','F8','F7','F3','Fz','F7','F3','Fz','F4','F7','F3','Fz'},...
         'BoxStyle','filled')

ylabel('Katz FD (OCD)')
